name: RedeemXBot
version: '1.0.0'
main: me.justlime.redeemxbot.RedeemXBot
api-version: '1.13'
depend: [RedeemX]
softdepend:
  - PlaceholderAPI

commands:
  codelink:
    description: "Links your Minecraft account to your Discord account."
    usage: "/linkdiscord"
    aliases: [discordlink, link]
